# Generated by Django 3.1.1 on 2020-09-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="is_candidate",
        ),
    ]
